name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy env.example
        run: cp .env.example .env

      - name: Start MySQL service
        run: docker-compose up -d mysql

      - name: Build and run tests
        run: |
          docker-compose run --rm laravel.test php artisan key:generate
          docker-compose run --rm laravel.test composer install --no-interaction
          docker-compose run --rm laravel.test php artisan migrate --env=testing
          docker-compose run --rm laravel.test vendor/bin/phpunit